### ISSUE TITLE
Use case: loading throbber

### ISSUE THREAD

**Issue by insin** [rackt/async-props#14]
If you wanted to have a "something is loading" throbber at the top level of your app to indicate loading with async-props is currently happening _somewhere_ in the route hierarchy, is there any way async-props can provide that information, or would you have to manage it externally via your static `loadProps` hooks?

**Comment by zackify** [comment]
I can think of a hack. Set this.loading = true at the top of loadProps and
set it to false when you do the callback. But I'm not sure of a proper way.

**Comment by insin** [comment]
Looks like the `asyncProps` object on the context has a `loading` property:

``` js
  contextTypes: {
    asyncProps: React.PropTypes.object
  },
  render() {
    let {loading} = this.context.asyncProps
    // ...
  }
```

**Comment by ryanflorence** [comment]
It already passes down a "loading" prop to your components.

https://github.com/rackt/async-props/blob/master/example/app.js#L36-L40

**Comment by insin** [comment]
@ryanflorence Is the `loading` prop that gets passed down for the global loading state? I was wondering about support for displaying global vs. route-specific loading indicators.
