### ISSUE TITLE
Wait on promise in addition to callback

### ISSUE THREAD

**Issue by jorrit** [rackt/async-props#17]
The current implementation only supports rendering after `loadProps` invokes a callback. Wouldn't it be an interesting addition to also support `loadProps` returning a Promise and render after the promises resolve?

**Comment by ryanflorence** [comment]
Gonna keep it simple and stick with callbacks.

I'd be more interested in figuring out some API to let you plug in this kind of behavior.

**Comment by ryanflorence** [comment]
Like, maybe its just a prop like `resolve` here: https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L184

**Comment by sars** [comment]
@jorrit @ryanflorence This should fix this problem https://github.com/rackt/async-props/pull/42
