### ISSUE TITLE
Extra parameters to `loadProps`

### ISSUE THREAD

**Issue by jorrit** [rackt/async-props#18]
I want to access my flux instance in `loadProps`. On the server side I can manipulate `params` to include my flux instance, but it feels a bit hacky, but on the client-side the invocation of `loadProps` is hidden by `RoutingContext={AsyncProps}`. What would be the best way to access a request-specific variable in `loadProps`?

**Comment by ryanflorence** [comment]
React Router 2.0 (which is coming in the next couple weeks) has a better API than `RoutingContext` to help you do this.

For now, you can make your flux instance a singleton, no? Then export it as a module and use it anywhere you want.

Also, there are two goals of this library, 1) to be useful, 2) to show how to build your own data loading abstraction, you can make your own `RoutingContext`.
