### ISSUE TITLE
throw error with react-router@1.0.2

### ISSUE THREAD

**Issue by ellemedit** [rackt/async-props#19]
Hi. I got an error in client-side:
<img width="662" alt="2015-12-25 3 28 12" src="https://cloud.githubusercontent.com/assets/2682865/11997163/a003e794-aab7-11e5-919c-c50328e2fc89.png">

client-side react render code:

```
  <Router history={history} createElement={AsyncProps}>
    <Route path="/" component={App}>
      <Route path="*" component={ContentPage} />
      <IndexRoute component={HomePage} />
    </Route>
  </Router>
```

RoutingContext attribute did not work on react-router@1.0.2, I tried `createElement` attributes as similar. Is there plan to fix it? or should I downgrade react-router?
- `renderProps` give 'undefined' components. so when check loadProps, there's need to filter undefined components as:

```
const components = renderProps.components.filter(x => !!x);
      renderProps.components = components;
```

Thank you!

**Comment by ryanflorence** [comment]
I can't reproduce this problem, the example in the repo works, I'll need more to go on than "doesn't work".

**Comment by ellemedit** [comment]
It was solved, sorry.
