### ISSUE TITLE
Rethink the script string

### ISSUE THREAD

**Issue by romeovs** [rackt/async-props#21]
I know it's been discussed in #4 but I want to bring it up again here.

The way the script thing works now, the user-land code gets handed a string of the form:

``` js
"<script>__ASYNC_PROPS__ = /* .... */ </script>"
```

This is quiet handy in the case you use js template strings to insert the script into your html (as shown in the README):

``` js
html = (markup, script) => `
  <html>
    <!-- ... -->
    ${markup}
    ${script} 
  </html>
`
```

I for one, do not use js string templates to generate my html, I use react components. To get the script working I now need to do either:

``` js
<span dangerouslySetInnerHTML={{__html: script }} />
```

which adds a superflous `<span>`. Or I can make my markup a bit cleaner with:

``` js
const data = script.replace(/^<script>/, '').replace(/<\/script>$/, '');
//...
<script dangerouslySetInnerHTML={{__html: data }} />
```

Both of these solutions seem a bit hacky. I prefer to keep `dangerouslySetInnerHTML` out of my code 
completely. I also would like to be able to minify the script code when in production.

How can we fix this? It seems like there are a lot of people who are fine with the way things are now, but
we should be able to expand the use-case to other users.

I propose the following: make the `script` parameter be an object that knows how to transform the data to any of the preferred forms (the string with script tags, the pure object, ....) so people can choose which they like. So people can call `script.asString()` or `script.data()` to be able to use their use case.

**Comment by zackify** [comment]
You can't set a doctype with react, so why would you want to return
components vs regular HTML with your components in the body?

**Comment by romeovs** [comment]
I use a component to build up complicated nested stuff (using `react-document-meta` for example), and then render everything to a string using `react-dom/server`s `renderToStaticMarkup`. Slapping on the
`<!doctype html>` to the front of the generated string is not that hard. 

Look, my HTML component looks like this:

``` js
import React    from 'react'
import pure     from 'pure-render-decorator'
import autobind from 'autobind-decorator'
import Meta     from 'react-document-meta'
import DOM      from 'react-dom/server'
import uglify   from 'uglify-js'

const PROD = process.env.NODE_ENV === 'production';
const Script = function ({ script }) {
  const data = script
    .replace(/^<script>/, '')
    .replace(/<\/script>$/,'');

  // only minify in production
  var min = PROD ? data : uglify.minify(data, {fromString: true}).code;

  return <script dangerouslySetInnerHTML={{__html: min}} />;
};

class Html extends React.Component {

  static propTypes = {
    component: React.PropTypes.node
  , string: React.PropTypes.string
  }

  render () {
    const {
      component
    , script
    } = this.props;
    const content = component ? DOM.renderToString(component) : 'no component';

    return (
      <html>
        <head>
          <meta charSet='utf-8' />
          <link rel='stylesheet' href='/assets/main.css' />
          <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
          {Meta.renderAsReact()}
        </head>
        <body className='nocsstransform'>
          <div
            id='app'
            dangerouslySetInnerHTML = {{ __html: content }}
          />
          <script src='/assets/modernizr.js' />
          <Script script={script} />
          <script src='/assets/main.js' />
        </body>
      </html>
    );
  }
};
```

I can render it using the render function:

``` js
const render = function (component, script) {
  const markup = DOM.renderToStaticMarkup(<Html component={component} script={script} />);
  return `<!doctype html>${markup}`;
};
```

eg.

``` js
const html = render(<AsyncProps {...props}/>, script);
```

I really like to use React as a html templating tool because this integrates well with things
like `react-document-meta` etc.

Note that I cannot just do

``` js
{/*....*/}
  <body>
    {script}
  </body>
</html>
```

Because React escapes the script tag (generating `&lt;script&gt; __ASYNC_PROPS = //...`, which isn't what I need).

**Comment by ryanflorence** [comment]
`dangerouslySetInnerHtml` works fine.

Since there's no alternative API proposed here, and the script string is still workable when using react for the base document, I'm closing the issue.

Happy to entertain an alternative API but I'm not personally going to spend time coming up with one.
