### ISSUE TITLE
Breaks createBrowserHistory

### ISSUE THREAD

**Issue by ghost** [rackt/async-props#24]
I just tried to use async-props with react-router, and `createBrowserHistory` and everything works fine apart from one thing:

Here's a short form of my code: 
 (CJSX) (React Router: 1.0.3, Async-props: 0.2.2 ) 

My routing file:

``` cjsx
ReactDom.render(    
    <Router RoutingContext={AsyncProps}  history={ createBrowserHistory() }>
        { routes }
    </Router>
,document.getElementById("app"))

```

And the components both look something like this. 

``` cjsx
class Home extends React.Component


    @contextTypes:
        history: require("react-router").PropTypes.history

    displayName: "Home"
```

I can call `@context.history.push` etc. and it navigates properly, but **if you use the back button in the browser nothing happens**. I tracked it down to the `RoutingContext`. When I remove it everything works. 

(Navigation using `<Link>` also works, but the back button is broken too)

I hope my explanation didn't sound too crazy and you somewhat understand my problem.. Thanks in advance!

**Comment by ryanflorence** [comment]
The example in the repo doesn't break the back button, I'm going to need more to go on than "this is broken". Happy to reopen if you can narrow down the problem. Thanks.
