### ISSUE TITLE
renderLoading prop doesn't work

### ISSUE THREAD

**Issue by ellemedit** [rackt/async-props#26]
Hi.
I tried to show loading message through `renderLoading` the callback never triggered.
Hope to pre-release for router@2.x or hot-fix it.

Thank you!

**Edit**
`renderLoading` is only used in first-loading in client-side. I got it incorrectly. Hope to add callback for every loading.

**Comment by ryanflorence** [comment]
renderLoading is only for the initial "we haven't even rendered anything yet in the client", `this.props.loading` comes into your route components, check out the example.
