### ISSUE TITLE
`loadProps` called twice

### ISSUE THREAD

**Issue by ellemedit** [rackt/async-props#28]
Hi.
loadProps is executed twice and loading time is also double.
Is there a reason? Or is it just a bug? It is in current master (not released, for react-router@2.x)

Thank you!

**Comment by ryanflorence** [comment]
Sounds like a bug, or a buggy implementation. The example in the repo doesn't call it twice, please provide a test case and I can reopen.

**Comment by ellemedit** [comment]
@ryanflorence My test code was:

``` js
// it's in `/example/app.js`
class Contact extends React.Component {

  static loadProps(params, cb) {
    console.log('twice');
    fetchContact(params.contactId, (err, contact) => {
      cb(null, { contact })
    })
  }
  ...
}
```

It prints out `twice` double when I clicked item of contact list. plz check it again. It happens when you are already in contact URL route.

e.g) **check out** in your example `Ryan Florence` => `Michael Jackson`
From index, to `Ryan Florence` is okay. From `Ryan Florence` to `Michael Jackson`? It exactly calls `loadProps` twice!

Thank you

**Comment by ellemedit** [comment]
And it calls `loadProps` even if there's `__ASYNC_PROPS__` variable from server-rendering.
Is this what you intended?

**Comment by AndrewIngram** [comment]
I'm also seeing the second issue regarding loadProps still being called even if there's data from the server-rendering. This isn't desirable behaviour, because I have a use case with a random list of data that suddenly changes when React loads on the client.

**Comment by dan-weaver** [comment]
@ryanflorence I just built the example and it does actually call it twice for me.

**Comment by dan-weaver** [comment]
It appears there is duplication of effort between the AsyncProps component and the AsyncPropsContainer maybe?

By commenting out

```
this.context.asyncProps.reloadComponent(nextProps.Component)
```

on line 150
the example at least seems to work as expected (loading once).

Not sure what other issues this introduces of course, pivot route tests fail, but such routes don't seem to fail in actual usage

**Comment by zackify** [comment]
@AndrewIngram @Beingbook This is desired, think about this: You load the page, you get the props from the server then again on the client. Now, you click away to another page, update some info via ajax, then click back to the page, and it fetches again for the latest data. Is there a good way the client can know if the page was server rendered vs you went to another page then came back? I don't think so.

**Comment by AndrewIngram** [comment]
I hope there is a good way, because it's kind of important. I have at least three uses cases at work where making the same data fetch twice in a row won't return the same data, and i'm sure I can think of some more with time. But in terms of server load alone, I don't want a potentially expensive data query being executed twice.

To clarify, what I'm saying is, when doing server-side rendering:
- For the very first client render, don't do the data fetch (I have no good ideas right now for how this should be implemented).
- For subsequent client renders (ie after navigation) do the data fetch.

However, i'm not sure the two issues being discussed in this ticket are the same, so it might be worth opening another one.

**Comment by zackify** [comment]
After throwing in isomorphic-fetch, I'm seeing the props twice before the client side async props stuff picks it up and called loadProps. So I wonder if something else is the issue, a parent component's props changing? Or something else. Trying to narrow it down.

**Comment by sars** [comment]
When router params changes the following are happening:
1. AsyncProps.componentWillReceiveProps is invoked. List of components inside is changed.
So loadAsyncProps is called here: https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L262
2. AsyncPropsContainer.componentWillReceiveProps is invoked.
routeParams was changed, so reloadComponent is called:
https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L158

I'm not sure why we need AsyncPropsContainer at all?
To pass props to child component?

**Comment by sars** [comment]
@AndrewIngram @Beingbook @zackify 
Guys, may be I'm mistaken, but I don's see the reason why we need to reload data on client, if we just fetched them on server and passed using global var to client
https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L240
We always fetch data on client....

But it seems there are 2 issues here... Previous comment was about another problem

**Comment by zackify** [comment]
I've found that if you implement this: 

``` js
shouldComponentUpdate(nextProps) {
    if(nextProps.result == this.props.result) return false
    return true
  }
```

It solves the issue for now. Check if the prop you are setting on callback gets changed. Then it will be rendered on server load, and then once more when it finishes loading on the client. 

@sars thanks for the explanation!

**Comment by zackify** [comment]
@AndrewIngram #45 is an idea I have that may help you fix your problem.

**Comment by ryanflorence** [comment]
Just FYI on this project, the code was written rather quickly on an airplane and seemed to generally work. I haven't had time to really dig in and make it solid, but I'm excited so many folks are experimenting with this.

Here is when I think `loadProps` should be called. If anybody's got the time, please make sure there's test coverage for these scenarios:

As far as I can tell, `loadProps` should be called under three circumstances:
1. Initial load
2. Route entered when not active previously
3. Params or parent (grandparent, etc.) params changed

To be clear, here are some tables given an initial load and then a transition from one path to another, and which components should have `loadProps` called on them given this route structure:

``` js
<Route path="/" component={App}>
  <Route path="/courses" component={Courses}>
    <Route path=":courseId" component={Course}>
      <Route path="assignments" component={Assignments}>
      <Route path="students" component={Students}>
    </Route>
    <Route path="messages" component={Messages}>
      <Route path=":messageId" component={Message}/>
    </Route>
  </Route>
</Route>
```

| Enter Deep | loadProps for |
| --- | --- |
| `/courses/1/assignments` | App, Courses, Course, Assignments |

| Parent to Child | loadProps for |
| --- | --- |
| `/courses` | App, Courses |
| `/courses/1` | Course |

| Parent to GrandChild | loadProps for |
| --- | --- |
| `/courses` | App, Courses |
| `/courses/1/assignments` | Course, Assignments |

| Child to Parent | loadProps for |
| --- | --- |
| `/courses/1` | App, Courses, Course |
| `/courses` | (none) |

| Grandchild to Parent | loadProps for |
| --- | --- |
| `/courses/1/assignments` | App, Courses, Course, Assignments |
| `/courses` | (none) |

| Siblings | loadProps for |
| --- | --- |
| `/courses/1/assignments` | App, Courses, Course, Assignments |
| `/courses/1/students` | Students |

| Neice to Aunt | loadProps for |
| --- | --- |
| `/courses/1/assignments` | App, Courses, Course, Assignments |
| `/messages` | Messages |

| Aunt to Neice | loadProps for |
| --- | --- |
| `/messages` | App, Courses, Messages |
| `/courses/1/assignments` | Course, Assignments |

| Cousins | loadProps for |
| --- | --- |
| `/courses/1/assignments` | App, Courses, Course, Assignments |
| `/messages/2` | Messages, Message |

| Param change | loadProps for |
| --- | --- |
| `/courses/1` | App, Courses, Course |
| `/courses/2` | Course |

| Parent param change | loadProps for |
| --- | --- |
| `/courses/1/assignments` | App, Courses, Course, Assignments |
| `/courses/2/assignments` | Course, Assignments |

**Comment by ntkoopman** [comment]
I created a patch to fix this somewhat. At least it should fix loadProps being called twice on every route change.

**Comment by ryanflorence** [comment]
alright, I revamped the test suite and am testing everything in that table:
https://github.com/ryanflorence/async-props/blob/master/modules/__tests__/AsyncProps-test.js#L195

and used react routers diffing of routes instead of our own:
https://github.com/ryanflorence/async-props/blob/master/modules/AsyncProps.js#L214-L242

I think it should do what (most of us) expect now, w/o the unnecessary calls to `loadProps`. If you think you've found a problem, please provide a test case.

Thanks :)
