### ISSUE TITLE
consider flattening __ASYNC_PROPS__ for client hydration

### ISSUE THREAD

**Issue by travi** [rackt/async-props#3]
First, thank you for releasing this library. I'm still fairly new to React and have been trying to learn it without jumping to the complexity of something like redux before it is necessary. This library fits very well in the space where I thought I would need to build something custom for myself.

With the goal of trying to keep complexity low, I've started with a setup that is a bit different than what is suggested here. For my server-side rendering, I am not using async-props, but am passing the initial props through a [custom `createElement` function](https://github.com/travi/travi.org-admin/blob/master/lib/server/view/route-renderer.jsx#L14-L18). The need for this custom function for such simple use cases still seems unnecessary, but thats a different topic.

Because of this approach, I have not differentiated between which props are needed for each of the routable components for that page load, but rather just have a flat object with all of my data for that page. Therefore, I have to [jump through a few extra hoops](https://github.com/travi/travi.org-admin/blob/master/lib/server/view/rendering-handler.js#L13-L21) and leverage some knowledge about which components should be rendered, which doesn't feel like it should be the responsibility for this layer of my app.

It sounds like the current state of this project is still a pretty early design, so I'm hoping that things could still be flexible enough to support this type of use case. Would it be reasonable to support a flattened object literal for `__ASYNC_PROPS__`, either instead of the current list of objects, or at least optionally? This would enable the flexibility to use async-props client-side with an alternative server-side rendering technique without the requirement to jump through hoops to match the expected list.

**Comment by ryanflorence** [comment]
> without jumping to the complexity of something like redux before it is necessary.

That's the idea :)

> I've started with a setup that is a bit different than what is suggested here.

If you want to break out of the abstraction then its on you to deal with the hoop jumping. The internal data structure is not public API. I'm not sure why you would want to use async props for data loading in the client but not the server.

> With the goal of trying to keep complexity low, I've started with a setup that is a bit different than what is suggested here.

I'm wondering what about async props is making you feel like you need to break away from it to decrease complexity.

Happy to talk about your use-case, but the internal state of AsyncProps, and the shape of the data it stores, won't ever be public API.
