### ISSUE TITLE
SSR issue with ReactRouter 2.0

### ISSUE THREAD

**Issue by arkist** [rackt/async-props#30]
HI :smiley:  
I'm testing master branch of this on my private universal app,
and encountered a problem on SSR.

``` js
// client
render(
  <Router
    history={this.history}
    render={props => (
      <AsyncProps {...props} />
    )}>
    {this.routes}
  </Router>
);

// server
// .. in `loadPropsOnServer`'s cb
renderToString(
  <AsyncProps {...renderProps} {...asyncProps} />
);
```

It works, but `checksum was invalid` warning occurs like this:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid.
...
(client) <noscript data-reacti
(server) <div data-reactid=".y`
```

I've tried `<Router render={props => <AsyncProps {...props} />} ...` instead of just `<AsyncProps />` on server side too, but it doesn't work. 
fetching and bind scriptString is fine, but App's react components render on client side, after intial server rendered.
am I missed something?

thanks

**Comment by sars** [comment]
Got the same warning....

**Comment by zackify** [comment]
Does this gist I made happen to help? https://gist.github.com/zackify/cda88b5456a84594383d Maybe you are rendering into the wrong place?

**Comment by sars** [comment]
check it please: https://github.com/bdefore/universal-redux/pull/46

**Comment by arkist** [comment]
@sars  You make my day! 
I have used `scriptTag` before but now I change it to `asyncProps.propsArray` instead, and problem solved. I had built HTML document using `<Html />` component instead of template string. maybe it's caused checksum problem.

**Comment by arkist** [comment]
@zackify  not fit on my case, but thanks anyway!

**Comment by zackify** [comment]
@arkist glad you figured it out!
