### ISSUE TITLE
redirectToLogin middleware

### ISSUE THREAD

**Issue by ChiefORZ** [rackt/async-props#33]
Hey,

I've implemented this approach into my boilerplate (isomorphic with dynamic component loading) for displaying a Progress Bar when a dynamic route is loading.

I got a very similar setup to the example 'auth-with-shared-root' provided in the react-router examples https://github.com/rackt/react-router/blob/master/examples/auth-with-shared-root/config/routes.js

Some childRoutes got an `onEnter` middleware.

``` js
{ onEnter: redirectToLogin,
  childRoutes: [
    // Protected routes that don't share the dashboard UI
    { path: '/user/:id',
      getComponent: (location, cb) => {
        require.ensure([], (require) => {
          cb(null, require('../components/User'))
        })
      }
    }
    // ...
  ]
},
```

Any of these endpoints get the error **Uncaught TypeError: Cannot read property 'loadProps' of undefined** when routing to them. But when i remove the `onEnter` method and require.ensure it directly thise work fine.

Do i have to pass different attributes when using onEnter??

**Comment by ChiefORZ** [comment]
I was having issues, because on the server-side i tried to load the props of components, even before i redirected to the correct url using

``` js
function redirectToDashboard(nextState, replace) {
  if (auth.loggedIn()) {
    replace('/')
  }
}
```

my `match` block on the server-side was looking something like that:

``` js
match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
  loadPropsOnServer(renderProps, (err, asyncProps) => {
    if (error) {
      res.status(500).send(error.message);
    }
    else if (redirectLocation) {
      res.redirect(302, redirectLocation.pathname + redirectLocation.search)
    }
    else if (renderProps) {
      res.send('<!doctype html>\n' +
        renderToString(
          <Html assets={ webpackIsomorphicTools.assets() } asyncProps={ asyncProps }>
            { __DISABLE_SSR__? null: <AsyncProps { ...renderProps } { ...asyncProps } /> }
          </Html>
        )
      );
    }
    else {
      res.status(404).send('Not found')
    }
  });
});
```

and i had to change it to:

``` js
match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
  if (error) {
    res.status(500).send(error.message);
  }
  else if (redirectLocation) {
    res.redirect(302, redirectLocation.pathname + redirectLocation.search)
  }
  else if (renderProps) {
    loadPropsOnServer(renderProps, (err, asyncProps) => {
      res.send('<!doctype html>\n' +
        renderToString(
          <Html assets={ webpackIsomorphicTools.assets() } asyncProps={ asyncProps }>
            { __DISABLE_SSR__? null: <AsyncProps { ...renderProps } { ...asyncProps } /> }
          </Html>
        )
      );
    });
  }
  else {
    res.status(404).send('Not found')
  }
});
```

**Comment by ryanflorence** [comment]
Mind sending a pull request showing this in the README.md?

**Comment by ChiefORZ** [comment]
@ryanflorence no props man, done it  #49

it seems you are overwhelmed with the Pull Requests we are making ;)
i could help you keeping this repo updated, if you like

**Comment by zackify** [comment]
This PR looks awesome i made a component that transitions the pages in and
out on route change but am not sure if I like it yet.
