### ISSUE TITLE
loadProps Nirvana

### ISSUE THREAD

**Issue by ChiefORZ** [rackt/async-props#34]
I discovered that the `static loadProps` method has to be defined in all Components, otherwise the async-props will not receive an callback and update - easy enough.

So i defined empty callbacks for testing purposes

``` js
statics: {
  loadProps: function(params, cb) {
    cb(null);
  }
}
```

funny thing: the `{ loading } = this.props` in the root component does get updated correctly but the `{ this.props.children }` does not recognize any changes...

so i had wo hack the system a bit and call it with an zero timeout and whoop - it works:

``` js
statics: {
  loadProps: function(params, cb) {
    setTimeout(function() {
      cb(null);
    },0);
  }
}
```

don't know it is an bug - or an feature :)

**Comment by zackify** [comment]
Sure you're on the latest version? This was fixed a while back.

**Comment by ChiefORZ** [comment]
Yes, I am.

If it helps, i uploaded the repo at https://github.com/ChiefORZ/super-sexy-react/tree/feature/async-props
make sure you are on the feature/async-props branch

**Comment by ChiefORZ** [comment]
#40 fixed it!

**Comment by zackify** [comment]
Yessss!

**Comment by ryanflorence** [comment]
this is fixed
