### ISSUE TITLE
loadProps in child route breaks <Link /> in react-router 2.0

### ISSUE THREAD

**Issue by zackify** [rackt/async-props#38]
When I have 

``` js
static loadProps(params, cb) {
  cb(null, { test: 'hi'})
}
```

inside a component, linking to that page does not work. The moment I remove the loadProps property and reload the page, using `<Link />` to that page works again. The url updates but the page does not actually switch unless you do a refresh.

Edit: Also noticed this only happens when loadProps is inside of a child route component.

**Comment by zackify** [comment]
Narrowed this down and submitted a PR #40. Looks like the component never got updated because the state never changed on route change.

**Comment by ryanflorence** [comment]
please try 0.3.0 and see if this is still a problem.
