### ISSUE TITLE
loadAsyncProps never fail?

### ISSUE THREAD

**Issue by sars** [rackt/async-props#41]
Hi there,

I noticed that callback passed to loadAsyncProps never fails: 
https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L40

so it looks like handleError doesn't make sense
https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L265

Did I miss something?

**Comment by ryanflorence** [comment]
It's intended the errors make their way all the way up, obviously they don't. Was just cranking out the code real quick on an airplane one day :)

**Comment by ryanflorence** [comment]
I think this is fixed, don't think there's a test though :\
