### ISSUE TITLE
Clicking on a <Link /> before loadProps on client side finishes causes failure to transition

### ISSUE THREAD

**Issue by zackify** [rackt/async-props#44]
To reproduce:

``` js
static loadProps(params, cb) {
  setTimeout(() => cb(null, {result: true}), 3000)
}
```

Render a page with `<Link />` and click on it within the first 3 seconds. The url will update, but the content doesn't, because AsyncProps breaks. Trying to figure out a solution.

**Comment by ryanflorence** [comment]
Think you can work up a failing test for this?

**Comment by zackify** [comment]
Doesn't happen anymore :)
