### ISSUE TITLE
npm-scripts/postinstall.js global babel

### ISSUE THREAD

**Issue by andresgutgon** [rackt/async-props#46]
## What?

This is just a question. I'm trying to introduce async-props into my package.json. I've babel as a dependency but async-props post install was failing when doing `npm install`.

Only after install babel globally the install worked. What I'm missing. It's necessary post install script?

**Comment by andresgutgon** [comment]
I see people is having the same problem as me: 
https://github.com/bdefore/universal-redux/blob/master/src/helpers/asyncProps.js#L1

What's the right way to install this package?

**Comment by andresgutgon** [comment]
What I'm doing now is:
1. `git clone git@github.com:rackt/async-props.git ~/some-where/in-my-machine/async-props` 
2. `cd ~/some-where/in-my-machine/async-props`
3. `npm install`
4. `npm run build`
5. `cd ~/my-project`
6. `npm install --save ~/some-where/in-my-machine/async-props`

Is there a better solution. In any case it would be great document it. Let me knwo if I can help there making a PR for adding documentation

**Comment by zackify** [comment]
Why can't you just install from npm? It is a little out of date, but I'm
confused with your problem.

**Comment by andresgutgon** [comment]
> Why can't you just install from npm?

npm version is conflicting with other package, also it has `react-router@>1.0.0-rc3` as peerDependency
![image](https://cloud.githubusercontent.com/assets/49499/12379832/b8ca2802-bd62-11e5-96e4-b00aa55e0591.png)

**Comment by AVVS** [comment]
use npm@3 and that wont be a problem any longer

**Comment by zackify** [comment]
Install npm 3 like Vitaly says and there's no problem. Or clone the repo
and push up the built version to your own npm repo.

**Comment by andresgutgon** [comment]
It's ok for know building it locally. Thank you. Closing it. 
Here there is not a problem just me not getting the situation :)

**Comment by evenchange4** [comment]
> use npm@3 and that wont be a problem any longer

I cannot use npm 3 for my project because of not all other packages support npm 3 yet.
Are there any suggestion about using `async-props` with npm `2.x` ?  :')

**Comment by ryanflorence** [comment]
You probably shouldn't be using Async Props on anything important, its only half-baked right now.

Next release we'll lighten up the peerDep (or remove it completely).

**Comment by zackify** [comment]
Oh man I'm using it on something pretty important right now, you're making
me nervous 😛 I could always disable the dynamic routing awesomeness if I
needed to I guess.
