### ISSUE TITLE
If no components define loadProps, loadPropsOnServer hangs

### ISSUE THREAD

**Issue by tomatau** [rackt/async-props#5]
When no components define static loadProps, loadPropsOnServer never fires it's callback.

**Comment by dlmr** [comment]
There is an active PR that fixes this. https://github.com/rackt/async-props/pull/2

**Comment by tomatau** [comment]
Just found it as I was about to submit a PR myself :) will leave this open for others to see until it's merged..

**Comment by ryanflorence** [comment]
fixed in #2
