### ISSUE TITLE
Setting Page Title from async-props

### ISSUE THREAD

**Issue by zackify** [rackt/async-props#59]
Hey, sometimes I need to set the page title based on something returned from an api. For now I've been doing something like this inside of `loadPropsOnServer`

``` js
if(asyncProps.propsArray[asyncProps.propsArray.length - 1].title) {
  title = asyncProps.propsArray[asyncProps.propsArray.length - 1].title
}
```

I'm just curious if @ryanflorence would like to add a better way to do this or if that is outside of the scope of this package.

**Comment by ryanflorence** [comment]
https://github.com/ryanflorence/react-title-component

also built into react-project.

**Comment by zackify** [comment]
Thanks, pretty simple code I see :)
