### ISSUE TITLE
componentWillReceiveProps logic missing some scenarios

### ISSUE THREAD

**Issue by insin** [rackt/async-props#9]
Here's an example where I'm going up the route tree from  a `/:user/:repo`  to a different `/:user`where there are User and Repo route components - it never gets to compare the `user` props against eachother so the user data doesn't get reloaded:

![async-props-cwrp](https://cloud.githubusercontent.com/assets/226692/11619459/242d7ace-9ca0-11e5-97b2-1e3a4ac425cc.png)

Seems like it should check the components one at time for equality them param changes inside this block.

Edit: live, heavy meta, example: https://insin.github.io/react-nwb-github-issues/#/rackt/async-props/9

**Comment by insin** [comment]
Another case: going from `/user1` to `/user2/repo` doesn't reload props for the `:user` route component - trying to turn these into failing test cases.

**Comment by insin** [comment]
Is it possible to determine which params were associated with which components via a Route in the context `AsyncProps` is operating in? It seems to me that needs to play a part in determining whether or not async props should be loaded.

Does this need to be or can it even be pushed down to the `AsyncPropsContainer` level?

**Comment by zackify** [comment]
Also, if I load a page initially, it shouldn't call loadProps on the frontend. Only when I navigate to a page client side should it call loadProps.

**Comment by insin** [comment]
Erm, I just got my tests to pass. The final trick was adding the extra tick function, which I now don't understand. Does any of this make sense?

`````` diff
diff --git a/modules/AsyncProps.js b/modules/AsyncProps.js
index 4623c63..0e0adf3 100644
--- a/modules/AsyncProps.js
+++ b/modules/AsyncProps.js
@@ -146,6 +146,14 @@ class AsyncPropsContainer extends React.Component {
     asyncProps: object.isRequired
   }

+  componentWillReceiveProps(nextProps) {
+    const paramsChanged = !shallowEqual(nextProps.routerProps.routeParams,
+                                        this.props.routerProps.routeParams)
+    if (paramsChanged) {
+      this.context.asyncProps.reloadComponent(nextProps.Component)
+    }
+  }
+
   render() {
     const { Component, routerProps } = this.props
     const { propsAndComponents, loading, reloadComponent } = this.context.asyncProps
diff --git a/modules/__tests__/AsyncProps-test.js b/modules/__tests__/AsyncProps-test.js
index 73807d9..f184f61 100644
--- a/modules/__tests__/AsyncProps-test.js
+++ b/modules/__tests__/AsyncProps-test.js
@@ -233,6 +233,7 @@ describe('AsyncProps', () => {
           history.pushState(null, '/1')
         },
         () => expect(div.textContent).toContain('heck yeah! cinnamon life'),
+        () => {},
         () => expect(div.textContent).toContain('heck yeah! berry berry kix'),
         done
       ])
:```
``````

**Comment by insin** [comment]
Here's a build of my app with PRs #2 (so the root route renders something) and #11 applied:

https://insin.github.io/react-nwb-github-issues/#/rackt/async-props/9

If you click on someone's name from the issue thread, it now does reload their async props, but it switches to a view of the current set of props first.

**Comment by ryanflorence** [comment]
follow #11
